config/routes.rb
Rails.application.routes.draw do
  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  # devise関連のルーティングは、他のルーティングよりも前に記述する必要がある（競合を避けるため）
  # usersのdevise routes
  devise_for :users, controllers: {
    # Twitterのomniauth認証を追加するためのルーティング
    omniauth_callbacks: 'users/omniauth_callbacks',
  }
  # userにゲストログイン機能を追加するためのルーティング
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  # adminsのdevise routes
  devise_for :admins, skip: :registrations

  # 本関連のルーティング
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  # ユーザー関連のルーティング
  resources :users, only: [:index,:show,:edit,:update] do
    member do
      get :following, :followers
    end
    resources :direct_messages, only: [:index, :create]
  end
  resources :relationships, only: [:create, :destroy]
  resources :groups, except: :destroy do
    resource :group_users, only: [:create, :destroy]
    resources :group_messages, only: [:new, :create, :show, :index]
  end
  # お天気情報のルーティング
  get 'weather_info/show'
  get "search"=>'searches#search'
  # タグ検索も検索のカテゴリ選択に含めれば良さそうだが、今回は教材の見た目通りに実装する
  get "tag_search"=>'tag_searches#search'

  # 管理者関連のルーティング
  namespace :admins do
    get 'dashboard', to: 'admins#dashboard'
    get 'users', to: 'admins#users'
    resources :admins, only: [:new, :create, :destroy]
  end
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :owner, class_name: 'User'
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users
  has_many :group_messages, dependent: :destroy

  has_one_attached :group_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  def get_group_image
    (group_image.attached?) ? group_image : 'no_image.jpg'
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]

  def index
    @groups = Group.all
    @book = Book.new
  end

  def show
    @group = Group.find(params[:id])
    @user = @group.owner
    @book = Book.new
  end

  def new
    @group = Group.new
  end

  def create
    @group = current_user.owned_groups.build(group_params)
    if @group.save
      redirect_to groups_path, notice: 'Group was successfully created.'
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    if @group.update(group_params)
      redirect_to groups_path, notice: "You have updated group successfully."
    else
      render :edit
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :introduction, :group_image)
  end

  def ensure_correct_user
    @group = Group.find(params[:id])
    @user = @group.owner
    unless @user == current_user
      redirect_to groups_path
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th></th>
      <th class="small">グループ名</th>
      <th class="small">紹介文</th></th>
      <th class="small">メンバー数</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% groups.each do |group| %>
      <tr>
        <td><%= image_tag group.get_group_image, size: '50x50' %></td>
        <td><%= link_to "#{group.name}", group_path(group.id) %></td>
        <td><%= group.introduction %></td>
        <td><%= group.users.count + 1 %></td>
        <td>
        <% if group.owner == current_user %>
          <%= link_to 'Edit', edit_group_path(group.id), class: "btn btn-success py-1" %>
        <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/groups/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>Create Group</h2>
    <%= form_with model: @group, local:true do |f| %>
      <%= render 'layouts/errors', obj: @group %>
      <div class="form-group">
        <%= f.label "グループ名" %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
      <div class="form-group">
        <%= f.label "紹介文" %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.label "グループ画像" %>
        <%= f.file_field :group_image, class: "form-control-file group_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.submit "Update Group", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/groups/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', readOnly: false, book: @book %>
    </div>

    <div class='col-md-8 offset-md-1'>
      <h2>Groups</h2>
      <%= render 'index', groups: @groups %>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>Create Group</h2>
    <%= form_with model: @group, local:true do |f| %>
      <%= render 'layouts/errors', obj: @group %>
      <div class="form-group">
        <%= f.label "グループ名" %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
      <div class="form-group">
        <%= f.label "紹介文" %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.label "グループ画像" %>
        <%= f.file_field :group_image, class: "form-control-file group_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.submit "Create Group", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/groups/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', readOnly: false, book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Group detail</h2>
  		<table class='table'>
        <thead>
          <tr>
            <th></th>
            <th class="small">グループ名</th>
            <th class="small">紹介文</th></th>
            <th class="small">メンバー</th>
            <th colspan="2"></th>
          </tr>
        </thead>
  		  <tbody>
          <tr>
            <td><%= image_tag @group.get_group_image, size: '50x50' %></td>
            <td><%= @group.name %></td>
            <td><%= @group.introduction %></td>
            <td>
              <%= @group.owner.name %>
            <% @group.users.each do |user| %>
              <%= user.name %>
            <% end %>
            </td>
            <td>
            <% if @group.owner == current_user %>
              <%= link_to 'Edit', edit_group_path(@group.id), class: "btn btn-success py-1" %>
            <% else %>
              <% if current_user.groups.include?(@group) %>
                <%= link_to 'Leave', group_group_users_path(@group.id), method: :delete ,class: "btn btn-danger py-1" %>
              <% else %>
                <%= link_to 'Join', group_group_users_path(@group.id), method: :post ,class: "btn btn-success py-1" %>
              <% end %>
            <% end %>
            </td>
            <td>
            <% if @group.owner == current_user %>
              <%= link_to 'Notice an Event', new_group_group_message_path(@group.id), class: "btn btn-success py-1 text-nowrap" %>
            <% end %>
            </td>
          </tr>
  		  </tbody>
      </table>
    <% if current_user == @group.owner || @group.users.include?(current_user) %>
      <h2>Message from owner</h2>
      <table class="table">
        <thead>
          <tr>
            <th>Title</th>
            <th>Content</th></th>
          </tr>
        </thead>
        <tbody>
          <tr>
          <% @group.group_messages.order(created_at: :desc).each do |message| %>
            <td><%= message.title %></td>
            <td><%= message.content %></td>
          <% end %>
          </tr>
        </tbody>
      </table>
    <% end %>
    </div>
  </div>
</div>