config/routes.rb
Rails.application.routes.draw do
  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  # devise関連のルーティングは、他のルーティングよりも前に記述する必要がある（競合を避けるため）
  # usersのdevise routes
  devise_for :users, controllers: {
    # Twitterのomniauth認証を追加するためのルーティング
    omniauth_callbacks: 'users/omniauth_callbacks',
  }
  # userにゲストログイン機能を追加するためのルーティング
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  # adminsのdevise routes
  devise_for :admins, skip: :registrations

  # 本関連のルーティング
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  # ユーザー関連のルーティング
  resources :users, only: [:index,:show,:edit,:update] do
    member do
      get :following, :followers
    end
    resources :direct_messages, only: [:index, :create]
  end
  resources :relationships, only: [:create, :destroy]
  resources :groups, except: :destroy do
    resource :group_users, only: [:create, :destroy]
    resources :group_messages, only: [:new, :create, :show, :index]
  end
  # お天気情報のルーティング
  get 'weather_info/show'
  get "search"=>'searches#search'
  # タグ検索も検索のカテゴリ選択に含めれば良さそうだが、今回は教材の見た目通りに実装する
  get "tag_search"=>'tag_searches#search'

  # 管理者関連のルーティング
  namespace :admins do
    get 'dashboard', to: 'admins#dashboard'
    get 'users', to: 'admins#users'
    resources :admins, only: [:new, :create, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:twitter]

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  # N:N relations of follow(active) and followed(passive) between users
  has_many :active_relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :passive_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  # N:N relations of direct messages between user_a and user_b
  has_many :sent_messages, class_name: 'DirectMessage', foreign_key: 'sender_id', dependent: :destroy
  has_many :received_messages, class_name: 'DirectMessage', foreign_key: 'receiver_id', dependent: :destroy
  # N:N relations between user_a and user_b through group_users
  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users
  has_many :owned_groups, class_name: 'Group', foreign_key: 'owner_id'

  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  def get_profile_image
    if profile_image.attached?
      Rails.application.routes.url_helpers.rails_blob_url(profile_image)
    else
      ActionController::Base.helpers.asset_path('no_image.jpg')
    end
  end

  def follow(other_user)
    active_relationships.create(followed_id: other_user.id) unless self == other_user
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy if following?(other_user)
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def self.search(word, method)
    if method == "完全一致"
      where(name: word)
    elsif method == "前方一致"
      where("name LIKE ?", "#{word}%")
    elsif method == "後方一致"
      where("name LIKE ?", "%#{word}")
    else
      where("name LIKE ?", "%#{word}%")
    end
  end

  def today_books
    self.books.where(created_at: Time.zone.now.all_day)
  end

  def yesterday_books
    self.books.where(created_at: 1.day.ago.all_day)
  end

  def this_week_books
    self.books.where(created_at: Time.zone.now.all_week)
  end

  def last_week_books
    self.books.where(created_at: 1.week.ago.all_week)
  end

  def percent_increase(current_period, last_period)
    if last_period.count == 0
      100
    else
      (((current_period.count - last_period.count) / last_period.count.to_f) * 100).round
    end
  end

  def self.guest
    find_or_create_by!(name: 'guestuser' ,email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def twitter
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: 'guestuserでログインしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    @today = Date.today
    @daily_books = (0..6).map do |days_ago|
      date = @today - days_ago
      books_count = @books.where(created_at: date.all_day).count
      [date, books_count]
    end.to_h
    if params[:date]
      @books_count = @user.books.where(created_at: params[:date].to_date.all_day).count
    else
      @books_count = 0
    end
    
    respond_to do |format|
      format.html
      format.js
    end
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  def following
    @users = User.find(params[:id]).following
  end

  def followers
    @users = User.find(params[:id]).followers
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
    elsif @user.name == "guestuser"
      redirect_to user_path(current_user), notice: 'ゲストユーザーはプロフィール画面へ遷移できません'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>
          <span class="small">フォロー数:</span><span><%= user.following.count %></span>
        </td>
        <td>
          <span class="small">フォロワー数:</span><span><%= user.followers.count %></span>
        </td>
        <td>
        <% unless user == current_user %>
          <% if current_user.following?(user) %>
            <%= link_to "フォローを外す", relationship_path(current_user.active_relationships.find_by(followed_id: user.id)), method: :delete, class: "small" %>
          <% else %>
            <%= link_to "フォローする", relationships_path(follower_id: current_user.id, followed_id: user.id), method: :post, class: "small" %>
          <% end %>
        <% end %>
        </td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th>
      <%= link_to "#{ user.following.count }", following_user_path(user.id) %>
    </th>
  </tr>
  <tr>
    <th>followers</th>
    <th>
      <%= link_to "#{ user.followers.count }", followers_user_path(user.id) %>
    </th>
  </tr>
  <tr>
  <% unless user == current_user %>
    <th>
      <% if current_user.following?(user) %>
        <%= link_to "フォロー外す", relationship_path(current_user.active_relationships.find_by(followed_id: user.id)), method: :delete, class: "btn btn-success btn-small px-1" %>
      <% else %>
        <%= link_to "フォローする", relationships_path(follower_id: current_user.id, followed_id: user.id), method: :post, class: "btn btn-success btn-small px-1" %>
      <% end %>
    </th>
    <th>
    <% if current_user.following?(user) && user.following?(current_user) %>
      <%= link_to 'chatを始める', user_direct_messages_path(user_id: user.id), class: "small" %>
    <% end %>
    </th>
  <% end %>
  </tr>
</table>

<% if user.name != "guestuser" %>
<div class='row'>
  <%= link_to edit_user_path(user), data: {"turbolinks"=>false} , class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>
<% end %>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :profile_image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*', id: 'image_preview' %>
      <% if @user.profile_image.attached? %>
        <%= image_tag @user.profile_image, width: 100, height: 100 %>
        <span> → </span>
      <% end %>
        <img id="preview" width="100" height="100">
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
  <%= javascript_pack_tag 'image_preview', async: false %>
</div>

app/views/users/followers.html.erb
<h1>Follower Users</h1>
<% if @users.count.zero? %>
  <p>ユーザーはいません</p>
<% else %>
  <%= render 'index',users: @users %>
<% end %>

app/views/users/following.html.erb
<h1>Follow Users</h1>
<% if @users.count.zero? %>
  <p>ユーザーはいません</p>
<% else %>
  <%= render 'index',users: @users %>
<% end %>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', readOnly: false, book: @book %>
    </div>

    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= link_to "グループを作成する", new_group_path, class: "small" %>
      <span> | </span>
      <%= link_to "グループ一覧", groups_path, class: "small" %>
      <span> | </span>
      <%= link_to "天気情報", weather_info_show_path, class: "small" %>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', readOnly: false, book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index', books: @books %>
      <h2>投稿数の前日比・前週比</h2>
      <table class='table table-bordered'>
        <thead>
          <tr>
            <th>今日の投稿数</th>
            <th>前日の投稿数</th>
            <th>前日比</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @user.today_books.count %></td>
            <td><%= @user.yesterday_books.count %></td>
            <td><%= @user.percent_increase(@user.today_books, @user.yesterday_books) %>%</td>
          </tr>
        </tbody>
      </table>
      <table class='table table-bordered'>
        <thead>
          <tr>
            <th>今週の投稿数</th>
            <th>前週の投稿数</th>
            <th>前週比</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @user.this_week_books.count %></td>
            <td><%= @user.last_week_books.count %></td>
            <td><%= @user.percent_increase(@user.this_week_books, @user.last_week_books) %>%</td>
          </tr>
        </tbody>
      </table>
      <h2>7日分の投稿数</h2>
      <table class='table table-bordered'>
        <thead>
          <tr>
            <th>6日前</th>
            <th>5日前</th>
            <th>4日前</th>
            <th>3日前</th>
            <th>2日前</th>
            <th>1日前</th>
            <th>今日</th>
          </tr>
        </thead>
        <tbody>
          <tr>
          <% @daily_books.values.reverse.each do |books_count| %>
            <td><%= books_count %></td>
          <% end %>
          </tr>
        </tbody>
      </table>
      <canvas id="myChart" data-books="<%= @daily_books.values.reverse.to_json %>"></canvas>
      <%= form_with url: user_path(@user), method: :get, local: false, class: "mt-3" do |f| %>
        <%= f.date_field :date, required: true %>
        <%= f.submit "検索" %>
      <% end %>
      <table class='table table-bordered mt-2'>
        <thead>
          <tr>
            <th>投稿数</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td id="books-count"><%= @books_count %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.js.erb
$("#books-count").text("<%= @books_count %>");